# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    depends_on:
      - redis
    build: ./
    env_file:
      - .env
    environment:
      HTTP_PROXY: "http://127.0.0.1:9981" 
      HTTPS_PROXY: "http://127.0.0.1:9981"
      #   MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      #   REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - ./:/app
    profiles: ["exclude-from-up"]
    network_mode: host

  redis:
    image: "redis/redis-stack-server:latest"
    network_mode: host
